### ISSUE TITLE
Backups not executing

### ISSUE THREAD

**Issue by murphyj21** [plus3it/dotc-artifactory#35]
currently backups are being staged at /var/backups but are not being pushed to S3/deleted from /var/backups.

**Comment by ferricoxide** [comment]
Any errors logged?

**Comment by ferricoxide** [comment]
Updated the cron job to try to capture failures

**Comment by ferricoxide** [comment]
Per #36, pending close

**Comment by ferricoxide** [comment]
Looks like that fixed it. No errors logged since prior note and checked the system content, this morning and found:

~~~
[builder@artifactory01 ~]$ aws s3 ls s3://artifactory-backup-bucket
                           PRE Backups/
                           PRE creds/
2017-11-15 20:41:26          0 rebuild
[builder@artifactory01 ~]$ aws s3 ls s3://artifactory-backup-bucket/Backups/
                           PRE /
                           PRE 20171129.010015/
[builder@artifactory01 ~]$ date
Thu Nov 30 15:03:26 UTC 2017
[builder@artifactory01 ~]$ aws s3 ls s3://artifactory-backup-bucket/Backups/20171129.010015/
                           PRE builds/
                           PRE etc/
                           PRE licenses/
                           PRE repositories/
2017-11-29 23:00:03      62092 artifactory.config.xml
2017-11-29 23:00:03         92 artifactory.properties
2017-11-29 23:36:29      86582 security.xml
[builder@artifactory01 ~]$ ls /var/backups
20171130.010016  lost+found

~~~

It would appear that it performed the 2017-11-29 backup at its expected time - creating the locally-staged date-directory. Then, at the expected move-time, performed the croned-out move of that directory. That move left room for the 2017-11-30 backup to be locally-staged (and will presumably also get moved to S3 when cron next runs its sweeper job).
